### ISSUE TITLE
example in amd folder not work in firefox 40.0.2

### ISSUE THREAD

**Issue by tianyuanzhonglu** [Microsoft/TypeScriptSamples#33]
only show "TypeScript HTML App", but no time show.
the same code work correctly in chrome 41.0.2272

**Comment by DanielRosenwasser** [comment]
Thanks for reporting this @tianyuanzhonglu. If you know a fix that would work, we'd be willing to take a pull request.

**Comment by DavidRouyer** [comment]
.innerText is not a standard property, so Firefox does not implement it. More details here : http://perfectionkills.com/the-poor-misunderstood-innerText/ and http://caniuse.com/#feat=innertext
Oddly, the example is working for me in Firefox 38.0.5 and Firefox 42.0a2.
